### ISSUE TITLE
How often does the interactive map get updated?

### ISSUE THREAD

**Issue by 3vivekb** [mapbox/osm-sidewalker#13]
How often does the interactive map get updated?

**Comment by tcql** [comment]
@3vivekb the map hasn't been receiving updates for some time. Sidewalk mapping isn't an active priority at the moment. 

All the tools (should) be here for you to run your own interactive map, though:

- Run osm-sidewalker
- [Build an mbtiles from the output](https://github.com/mapbox/osm-sidewalker#publishing) and upload to your mapbox account as a new tileset
- Make a style that uses your newly uploaded tileset as a layer

If all you want is to have access to the data, you're done. If you want the full interactive UI
 
- Check out the `mb-pages` branch of this repo 
- You can [change the style id](https://github.com/mapbox/osm-sidewalker/blob/68afc94a20610c9cd036762f92099604faa26b00/index.src.js#L9) to point at your new style
- Use `npm install && npm run build` to regenerate the compiled javascript assets
- Use something like [serve](https://www.npmjs.com/package/serve) to run a quick local webserver so you can view the page

**Comment by 3vivekb** [comment]
That certainly answers my question!  At some point i'll have to re-run this code to check on the sidewalks.
